name: GitHubワークフローでHello Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: 文字をecho
        run: echo "GitHub Actionから Hello!!"
      - name: Pythonで文字をprint
        run: print("GitHub Actionで Pythonで Hello!!!")
        shell: python
        
